"""empty message

Revision ID: 2608b8a0354a
Revises: 52a2cb489f82
Create Date: 2016-10-18 19:45:10.210220

"""

# revision identifiers, used by Alembic.
revision = '2608b8a0354a'
down_revision = '52a2cb489f82'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('created', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'created')
    ### end Alembic commands ###
