"""empty message

Revision ID: a50c11b4a56f
Revises: c31261deb6d0
Create Date: 2016-10-18 16:00:08.007191

"""

# revision identifiers, used by Alembic.
revision = 'a50c11b4a56f'
down_revision = 'c31261deb6d0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('room', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'room')
    ### end Alembic commands ###
