"""empty message

Revision ID: c31261deb6d0
Revises: 05d8b15a8149
Create Date: 2016-10-16 22:45:02.010337

"""

# revision identifiers, used by Alembic.
revision = 'c31261deb6d0'
down_revision = '05d8b15a8149'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=250), nullable=True),
    sa.Column('created', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    ### end Alembic commands ###
